services:
    # mongodb: 
    #   image: mongo
    #   restart: always
    #   environment:
    #     MONGO_INITDB_ROOT_USERNAME: admin
    #     MONGO_INITDB_ROOT_PASSWORD: admin
    #   ports:
    #   - 27017:27017
    # redisdb:
    #   image: redis:7.2
    #   restart: always
    #   ports:
    #   - 6379:6379
    mysql:
      image: mysql:8.3
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: 'mysql'
        MYSQL_ROOT_USERNAME: 'mysql'
        MYSQL_ROOT_HOST: 'localhost'
        MYSQL_ROOT_DATABASE: 'mysql'
      ports:
      - 3306:3306
      expose: 
      - '3306'
